version: "3.8"

services:
  db:
    image: postgres:16
    container_name: db_app
    restart: always
    environment:
      POSTGRES_DB: sl_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: fastapi_short_link
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: sl_db
    restart: always

volumes:
  pg_data: