version: "3.7"
services:
  db:
    image: postgres:16
    container_name: db_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sl_db
    ports:
      - "1221:5432"
    expose:
      - "1221"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: fast_api_short_link
    command: ["/fast_api_short_link/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:mysecretpassword@db:5432/fastapi_links
      - PYTHONPATH=/fast_api_short_link

volumes:
  postgres_data:
  